### ISSUE TITLE
Build error when adding MDX support (or running the included example)

### ISSUE THREAD

**Issue by bjrn** [fastly/next-compute-js#5]
**Version**
```
Fastly CLI version v3.3.0 (96b3aa7)
Built with go version go1.19 linux/amd64
Viceroy version: viceroy 0.2.15
```

**What happened**

Setting a minimal site up from scratch works, but fastly compute serve fails when adding MDX. (Since MDX support is also in the example app in this repo, the example fails in the same way.)

running
`$ next build && cd compute-js && fastly compute serve`

```
✓ Verifying local javascript toolchain...
✗ Building package using javascript toolchain...

ERROR: error during execution process:

Warning: Unknown file type /.next/BUILD_ID...
Warning: Unknown file type /.next/trace...
Warning: Unknown file type /README.md....
```

**Comment by bjrn** [comment]
Hi, any updates or suggestions for workarounds here? @harmony7? I can get the Next.js-site in the examples folder to build if I comment out all MDX-related things in the example, but not as-is …

**Comment by harmony7** [comment]
Hi there, thanks for the comment.

The following needs to be done to the `next.config.js` file in the example, and this had inadvertently been left out of the files that got committed for the example.

I've committed an updated version to the repo and added a description to the README as well.
```
// Whatever your current next.config.js is
module.exports = {
  reactStrictMode: true,
  async headers() {
    return [
      {
        source: '/foo',
        headers: [
          {
            key: 'x-custom-header',
            value: 'my custom header value',
          },
        ],
      },
    ]
  },
};

if (!process.env.NEXT_COMPUTE_JS) {
  // Apply MDX loader only at compile time
  const withMDX = require('@next/mdx')({
    extension: /\.mdx?$/,
    options: {
      remarkPlugins: [],
      rehypePlugins: [],
    },
  });
  module.exports = withMDX({
    ...module.exports,
    // Append the default value with md extensions
    pageExtensions: ['ts', 'tsx', 'js', 'jsx', 'md', 'mdx'],
  });
}
```

Some of the dependencies that the `@next/mdx` plugin tries to load has problems with the Compute@Edge environment, and since this plugin actually only runs at compile time, we leave it out for runtime (It only needs to run during `next build` -- as it has the job of converting your `.mdx` files into `.js` files).

Please see if this helps.

**Comment by bjrn** [comment]
Thanks for the update, it worked great! And as you mention, `.mdx` compilation happens in the build step for my use case :+1:
